FROM python:3.13-slim-bookworm AS base

ENV \
  # https://docs-python.ru/standart-library/modul-faulthandler-python/
  # Трассировка Python сохраняется (даже при ошибках сегментации)
  PYTHONFAULTHANDLER=1 \
  # https://github.com/aws/amazon-sagemaker-examples/issues/319#issuecomment-405749895
  # Выходные данные Python отправляются прямо на терминал
  PYTHONUNBUFFERED=1 \
  # prevents python creating .pyc files
  PYTHONDONTWRITEBYTECODE=1

RUN <<EOF
apt-get update --quiet
apt-get install --quiet --no-install-recommends --assume-yes \
  make \
  jq \
  libzbar0 \
  git \
EOF


FROM base AS uv
COPY --from=ghcr.io/astral-sh/uv:0.7.20 /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1 \
  UV_LINK_MODE=copy \
  UV_PYTHON_DOWNLOADS=0

WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=bind,source=uv.lock,target=uv.lock \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  uv sync --locked --no-install-project --no-dev
COPY . /app
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync --locked --no-dev


FROM uv AS dev

WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
  uv sync

ENV PATH="/app/.venv/bin:$PATH"


FROM base AS prod

COPY --from=uv --chown=app:app /app /app
ENV PATH="/app/.venv/bin:$PATH"