
FROM python:3.13-slim-bookworm AS python-base

ARG poetry_version

ENV \
  # https://docs-python.ru/standart-library/modul-faulthandler-python/
  # Трассировка Python сохраняется (даже при ошибках сегментации)
  PYTHONFAULTHANDLER=1 \
  # https://github.com/aws/amazon-sagemaker-examples/issues/319#issuecomment-405749895
  # Выходные данные Python отправляются прямо на терминал
  PYTHONUNBUFFERED=1 \
  # prevents python creating .pyc files
  PYTHONDONTWRITEBYTECODE=1 \
  # Отключение кэширования
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  # Poetry's configuration:
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_IN_PROJECT=1 \
  POETRY_HOME="/opt/poetry" \
  POETRY_VERSION=${poetry_version} \
  # paths
  # this is where our requirements + virtual environment will live
  PYSETUP_PATH="/opt/pysetup" \
  VENV_PATH="/opt/pysetup/.venv"

# prepend poetry and venv to path
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

RUN apt-get update && apt-get install -y --no-install-recommends \
  make \
  jq \
  libzbar0 \
  git \
  # Удалить списки пакетов, загруженные apt update
  && apt clean \
  # Удалить кэшированные пакеты, загруженные apt install или apt upgrade
  && rm -rf /var/lib/apt/lists/*


# `builder-base` stage is used to build deps + create our virtual environment
FROM python-base AS builder-base

RUN apt-get update && apt-get install -y --no-install-recommends curl
RUN curl -sSL https://install.python-poetry.org | python3 -

# copy project requirement files here to ensure they will be cached.
WORKDIR $PYSETUP_PATH
COPY backend/poetry.lock backend/pyproject.toml ./

# install runtime deps - uses $POETRY_VIRTUALENVS_IN_PROJECT internally
RUN poetry install \
  --only main \
  --no-ansi \
  --no-root


# `development` image is used during development / testing
FROM python-base AS dev
WORKDIR $PYSETUP_PATH

# copy in our built poetry + venv
COPY --from=builder-base $POETRY_HOME $POETRY_HOME
COPY --from=builder-base $PYSETUP_PATH $PYSETUP_PATH

# quicker install as runtime deps are already installed
RUN poetry install --with=dev

# will become mountpoint of our code
WORKDIR /app


# `production` image used for runtime
FROM python-base AS prod
COPY --from=builder-base $PYSETUP_PATH $PYSETUP_PATH