"""ofd

Revision ID: 6f809c8d059d
Revises: 5257a71e1ea9
Create Date: 2025-04-18 19:07:56.289742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f809c8d059d'
down_revision: Union[str, None] = '5257a71e1ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofd_receipts',
    sa.Column('qrraw', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('user_inn', sa.String(), nullable=False),
    sa.Column('seller_address', sa.String(), nullable=True),
    sa.Column('retail_place', sa.String(), nullable=False),
    sa.Column('retail_place_address', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('credit_sum', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.Integer(), nullable=False),
    sa.Column('total_sum', sa.BigInteger(), nullable=False),
    sa.Column('buyer_phone_or_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('qrraw')
    )
    op.create_table('ofd_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('items_quantity_measure', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['ofd_receipts.qrraw'], name='ofd_items_receipt_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofd_items')
    op.drop_table('ofd_receipts')
    # ### end Alembic commands ###
