"""remove_unused_models

Revision ID: 5ff0e43a445b
Revises: 6f809c8d059d
Create Date: 2025-08-14 18:55:59.719651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ff0e43a445b'
down_revision: Union[str, None] = '6f809c8d059d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('masters')
    op.drop_table('services')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appointment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('appointment_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', name='genderenum'), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.master_id'], name=op.f('applications_master_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name=op.f('applications_service_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('applications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('applications_pkey'))
    )
    op.create_table('masters',
    sa.Column('master_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('master_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('master_id', name=op.f('masters_pkey'))
    )
    op.create_table('services',
    sa.Column('service_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('service_id', name=op.f('services_pkey'))
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('users_pkey'))
    )
    # ### end Alembic commands ###
